### PR TITLE
[ci skip] [cf admin skip] ***NO_CI*** adding bot automerge

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've added bot automerge as instructed in #60.

Merge this PR to enable bot automerging.

### CODE REVIEW

**Comment by jochym** [comment]
@brandon-rhodes could you look at the failure in this PR? It is inside the assay tool and I do not understand the reason...
I understand assay is your creation - maybe it will be clear to you?

**Comment by brandon-rhodes** [comment]
I will try this week to update assay with a more informative error message in this case. I have seen it in CI before but never locally, which makes it very hard to track down since I have no way to reproduce it.

**Comment by jochym** [comment]
Can I do anything to fix it? This is just re-run of the 1.40 build and should go smoothly. That is why I am surprised.

**Comment by brandon-rhodes** [comment]
@jochym — I spent today investigating, and have successfully landed a fix for "assay" under recent versions of Python 3, where Python pickles no longer interact in a friendly manner with unbuffered pipes (which were never a problem before, alas).

Here's the fix, for anyone curious:

https://github.com/brandon-rhodes/assay/commit/74fdfadd0ac593270b6cf09ccbfb4474bccb6a6e

As long as you're pulling the most recent "master" for assay, things should be fine; if instead you've vendored it, try pulling a new zip or tar.gz and your tests should start working again.

**Comment by jochym** [comment]
Thanks @brandon-rhodes . I have fixed (or work-aroudeed) it by removing --batch option. The tests are downloading the tgz from github. I will try to rebuild with a new master.

**Pull request merged**
