### PR TITLE
Update sgp4 requirement to 2.2

### PR DESCRIPTION
**Pull request by jochym**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Review by brandon-rhodes — APPROVED** [review]

**Comment by brandon-rhodes** [comment]
@jochym Is there any way to have the conda requirements mirror the requirements in the `setup.py`, to save you having to increment them somewhere else with each release? Is there any way the data can be better advertised in Skyfield itself to save you the effort?

**Comment by jochym** [comment]
@brandon-rhodes I am not sure if there is such a tool. It is not so easy to extract data realiably from setup.py. Probably requrements.txt are better. Actually I think good tests may be better. I think my testing procedure is different from what you are using now. Would you please check the test part of the meta.yaml file?

**Comment by brandon-rhodes** [comment]
> I think my testing procedure is different from what you are using now. Would you please check the test part of the meta.yaml file?

Ah, yes, thanks for asking — if you check out the script `test-code.sh` at the repository root, you'll find code that hopefully you can adapt to running in your feedstock.

**Comment by jochym** [comment]
I have spotted it but it does use a tool I am not familiar with (assay). The pypi record for it is rather sparse. Could you point me to it?

**Comment by brandon-rhodes** [comment]
It's a test framework of my own because I didn't like the other ones. I guess I should do a release at some point! For the moment, to get the feedstock moving more quickly for you, could you install it from the following URL ­— is that possible during the testing phase of a feedstock?

     pip install https://github.com/brandon-rhodes/assay/archive/master.zip

**Comment by brandon-rhodes** [comment]
@jochym — In case it's helpful in avoiding large downloads like the big hip_main file: Skyfield has all the files it should need to run its tests in the `ci/` directory. My own CI script copies them into the current directory before running the tests:

https://github.com/skyfielders/python-skyfield/blob/master/.travis.yml#L21

**Comment by jochym** [comment]
@brandon-rhodes The problem is this data is not present in the pypi package. But if we choose to use GitHub tarballs we will end up downloading even more data - so this approach actually saves bandwidth (downloads only if build is successful). The strange thing is I needed to only download hip for all tests to pass. Would you please take a look at build logs if everything is OK. I will wait for your approval before merging

**Comment by brandon-rhodes** [comment]
> The problem is this data is not present in the pypi package.

That makes sense! I'm so used to doing everything out of the repo that I didn't think through what would and wouldn't be available the next step downstream.

I've looked over the build and the test results look valid — none look to be missing, and they all passed. I think you may have succeeded.

**Comment by brandon-rhodes** [comment]
> I am not sure if there is such a tool. It is not so easy to extract data realiably from setup.py.

Let me know if an alternative form of configuration, like a `setup.cfg` file or something, could supplement Skyfield's metadata in a way that would make it easier for conda to track its dependencies, as this will probably happen every few releases or so; the requirements rarely stay static for long.

**Comment by jochym** [comment]
Thanks @brandon-rhodes. I'll try to take a closer look at the dependency menagement in conda-forge and I'll tell you if you can help in some way by using some alternative/additional metadata.

**Pull request merged**
